package delivery

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/minhtri2710/munsu/internal/ghurl"
	"github.com/minhtri2710/munsu/internal/task"
)

// PRCheck runs `munsu pr-check <id> <pr-url>`.
// It records the PR URL and head SHA in task meta, and writes a check.sh
// script that polls the PR merge status via `gh pr view`.
func PRCheck(homeDir string, id, prURL string) error {
	// Parse the PR URL
	ghURL, err := ghurl.ParseGHURL(prURL)
	if err != nil {
		return fmt.Errorf("invalid PR URL: %w", err)
	}

	// Fetch the PR head SHA via gh CLI
	headSHA, err := fetchPRHeadSHA(ghURL)
	if err != nil {
		return fmt.Errorf("fetching PR head SHA: %w", err)
	}

	// Read existing meta (ignore error if it doesn't exist)
	meta, err := task.ReadMeta(homeDir, id)
	if err != nil {
		meta = make(map[string]string)
	}

	// Write PR info to meta
	meta["pr"] = prURL
	meta["pr_head"] = headSHA

	if err := task.WriteMeta(homeDir, id, meta); err != nil {
		return fmt.Errorf("writing task meta: %w", err)
	}

	// Resolve project name for fleet-sync in check.sh script
	project := meta["project"]
	if project == "" {
		project = ghURL.Repo
	}

	// Write check.sh script
checkScript := fmt.Sprintf(`#!/bin/bash
# PR merge poll script for task %s
# Generated by munsu pr-check
set -euo pipefail

PR_NUM=%d
OWNER=%s
REPO=%s
HOME_DIR=%s
PROJECT=%s

echo "Polling PR #${PR_NUM} merge status for %s/%s..."
RESULT=$(gh pr view "${PR_NUM}" --repo "${OWNER}/${REPO}" --json merged 2>&1 || echo "ERROR:$?")

if echo "$RESULT" | grep -q '"merged": true'; then
	echo "merged: true"
	# Best-effort fleet-sync the project clone
	munsu --home "$HOME_DIR" fleet-sync "$PROJECT" 2>/dev/null || echo "Warning: fleet-sync for ${PROJECT} failed" >&2
	exit 0
elif echo "$RESULT" | grep -q '"merged": false'; then
	echo "merged: false"
	exit 1
else
	echo "error: unexpected response: $RESULT"
	exit 2
fi
`, id, ghURL.Num, ghURL.Owner, ghURL.Repo, homeDir, project, ghURL.Owner, ghURL.Repo)

	checkPath := filepath.Join(task.StateDir(homeDir), id+".check.sh")
	if err := os.MkdirAll(filepath.Dir(checkPath), 0755); err != nil {
		return fmt.Errorf("creating state directory: %w", err)
	}
	if err := os.WriteFile(checkPath, []byte(checkScript), 0755); err != nil {
		return fmt.Errorf("writing check script: %w", err)
	}

	fmt.Printf("PR check armed for %s (PR #%d)\n", ghURL.FormatPRRef(), ghURL.Num)
	fmt.Printf("  PR URL:   %s\n", prURL)
	fmt.Printf("  Head SHA: %s\n", headSHA)
	fmt.Printf("  Check:    %s\n", checkPath)
	return nil
}

// fetchPRHeadSHA fetches the head SHA of a PR via `gh pr view`.
func fetchPRHeadSHA(ghURL ghurl.GHURL) (string, error) {
	cmd := exec.Command("gh", "pr", "view",
		fmt.Sprintf("%d", ghURL.Num),
		"--repo", fmt.Sprintf("%s/%s", ghURL.Owner, ghURL.Repo),
		"--json", "headRefOid",
		"--jq", ".headRefOid",
	)
	out, err := cmd.Output()
	if err != nil {
		if ee, ok := err.(*exec.ExitError); ok {
			return "", fmt.Errorf("gh pr view: %s", strings.TrimSpace(string(ee.Stderr)))
		}
		return "", fmt.Errorf("gh pr view: %w", err)
	}
	return strings.TrimSpace(string(out)), nil
}
