package fleet

import (
	"fmt"
	"github.com/minhtri2710/munsu/internal/domain"
	"os"
	"path/filepath"

	"github.com/minhtri2710/munsu/internal/home"
)

// MRLiveCheck runs the GitLab MR equivalent of PRCheck.
// It captures the full delivery identity (MR URL, head SHA, source/target branch,
// owner, repo, provider, and timestamp) in task meta and writes a .check
// script that invokes the provider-neutral `munsu delivery merge-status` command.
// Never embeds raw glab in the script.
func MRLiveCheck(homeDir string, id, mrURL string) error {
	// Capture the full delivery identity atomically via typed GitLabClient
	ident, err := CaptureIdentity(mrURL)
	if err != nil {
		return fmt.Errorf("capturing delivery identity: %w", err)
	}

	// Validate identity before persisting
	if err := domain.ValidateIdentity(ident); err != nil {
		return fmt.Errorf("captured identity is incomplete: %w", err)
	}

	// Read existing meta (ignore error if it doesn't exist)
	meta, err := home.ReadMeta(homeDir, id)
	if err != nil {
		meta = make(map[string]string)
	}

	// Write full delivery identity to meta
	for k, v := range ident.ToMeta() {
		meta[k] = v
	}
	meta["pr"] = mrURL                                         // legacy key for compatibility
	meta["pr_head"] = ident.HeadSHA                            // legacy key for compatibility
	meta[MetaDeliveryState] = string(DeliveryStateReviewReady) // initialize lifecycle

	if err := home.WriteMeta(homeDir, id, meta); err != nil {
		return fmt.Errorf("writing task meta: %w", err)
	}

	// Write provider-neutral .check script that uses the munsu CLI seam
	checkScript := fmt.Sprintf(`#!/bin/bash
# MR merge poll script for task %s
# Generated by munsu mr-check (GitLab)
set -euo pipefail

TASK_ID="%s"
HOME_DIR="%s"

echo "Polling MR merge status for task ${TASK_ID}..."
if munsu --home "$HOME_DIR" delivery merge-status "${TASK_ID}" 2>/dev/null; then
	echo "merged: true"
	exit 0
else
	RESULT=$?
	echo "merged: false (exit code ${RESULT})"
	exit 1
fi
`, id, id, homeDir)

	checkPath := filepath.Join(home.StateDir(homeDir), id+".check")
	if err := os.MkdirAll(filepath.Dir(checkPath), 0755); err != nil {
		return fmt.Errorf("creating state directory: %w", err)
	}
	if err := os.WriteFile(checkPath, []byte(checkScript), 0755); err != nil {
		return fmt.Errorf("writing check script: %w", err)
	}

	fmt.Printf("MR check armed for %s/%s!%d\n", ident.Owner, ident.Repo, ident.Number)
	fmt.Printf("  MR URL:   %s\n", mrURL)
	fmt.Printf("  Head SHA: %s\n", ident.HeadSHA)
	fmt.Printf("  Provider: %s\n", ident.Provider)
	fmt.Printf("  Check:    %s\n", checkPath)
	return nil
}

// MergeStatus reports the merge status for a task with a delivery identity.
// Exit status: 0 = merged, 1 = not merged, 2 = error/unverifiable.
// Used as the provider-neutral watcher seam invoked by .check scripts.
func MergeStatus(homeDir, id string) error {
	ident, err := RequireIdentity(homeDir, id)
	if err != nil {
		return fmt.Errorf("cannot read delivery identity: %w", err)
	}

	status, err := QueryDeliveryMergeStatus(ident)
	if err != nil {
		return fmt.Errorf("merge status query: %w", err)
	}

	if status.Merged {
		fmt.Printf("%s/%s#%d merged (state=%s, head=%s)\n",
			ident.Owner, ident.Repo, ident.Number, status.State, status.HeadSHA)
		return nil
	}

	if status.Closed {
		fmt.Printf("%s/%s#%d closed (not merged, state=%s)\n",
			ident.Owner, ident.Repo, ident.Number, status.State)
		return fmt.Errorf("MR %d is closed but not merged (state=%s)", ident.Number, status.State)
	}

	fmt.Printf("%s/%s#%d open (not merged, state=%s)\n",
		ident.Owner, ident.Repo, ident.Number, status.State)
	return fmt.Errorf("MR %d is open and not merged (state=%s)", ident.Number, status.State)
}
