package fleet

import (
	"errors"
	"fmt"
	"github.com/minhtri2710/munsu/internal/domain"
	"os"
	"path/filepath"

	"github.com/minhtri2710/munsu/internal/home"
	"github.com/minhtri2710/munsu/internal/taskauthority"
)

// PRCheck runs `munsu pr-check <id> <pr-url>`.
// It captures the full delivery identity (PR URL, head SHA, head ref, base ref,
// owner, repo, provider, and timestamp) and routes it through the composed Task
// Authority as the generation-bound delivery preparation (Task 7.5), then
// writes a check.sh script that polls the PR merge status via `gh pr view`.
// On detecting a merged PR, the check.sh script also runs
// `munsu fleet sync` to sync the project clone.
func PRCheck(homeDir string, id, prURL string, auth *taskauthority.Authority) error {
	if auth == nil {
		return fmt.Errorf("pr-check: requires a composed task authority")
	}

	// Capture the full delivery identity atomically
	ident, err := CaptureIdentity(prURL)
	if err != nil {
		return fmt.Errorf("capturing delivery identity: %w", err)
	}

	// Validate identity before routing
	if err := domain.ValidateIdentity(ident); err != nil {
		return fmt.Errorf("captured identity is incomplete: %w", err)
	}

	// Route the delivery preparation through the composed Authority (Task
	// 7.5): the generation-bound prepare record commits with the identity
	// and review-ready state, and the identity meta keys are reconciled as a
	// post-commit projection. A projection failure returns a typed partial
	// error and never rolls back the authoritative commit.
	if _, err := StoreDeliveryPrepare(homeDir, auth, id, ident); err != nil {
		var projErr *DeliveryProjectionError
		if errors.As(err, &projErr) {
			fmt.Fprintf(os.Stderr, "Warning: delivery projection failed: %v\n", projErr)
		} else {
			return fmt.Errorf("pr-check: delivery preparation: %w", err)
		}
	}

	// Resolve project name for fleet-sync in check.sh script
	meta, err := home.ReadMeta(homeDir, id)
	if err != nil {
		meta = make(map[string]string)
	}
	project := meta["project"]
	if project == "" {
		project = ident.Repo
	}

	// Write check.sh script
	checkScript := fmt.Sprintf(`#!/bin/bash
# PR merge poll script for task %s
# Generated by munsu pr-check
set -euo pipefail

PR_NUM=%d
OWNER=%s
REPO=%s
HOME_DIR="%s"
PROJECT="%s"

echo "Polling PR #${PR_NUM} merge status for %s/%s..."
RESULT=$(gh pr view "${PR_NUM}" --repo "${OWNER}/${REPO}" --json state 2>&1 || echo "ERROR:$?")

if echo "$RESULT" | grep -q '"state":"MERGED"\|"state": "MERGED"'; then
	echo "merged: true"
	# Best-effort fleet-sync the project clone
	munsu --home "$HOME_DIR" fleet sync "$PROJECT" 2>/dev/null || echo "Warning: fleet sync for ${PROJECT} failed" >&2
elif echo "$RESULT" | grep -q '"state":"OPEN"\|"state": "OPEN"'; then
	echo "merged: false"
	exit 1
elif echo "$RESULT" | grep -q '"state":"CLOSED"\|"state": "CLOSED"'; then
	echo "merged: false (closed)"
	exit 1
else
	echo "error: unexpected response: $RESULT"
	exit 2
fi
`, id, ident.Number, ident.Owner, ident.Repo, homeDir, project, ident.Owner, ident.Repo)

	checkPath := filepath.Join(home.StateDir(homeDir), id+".check")
	if err := os.MkdirAll(filepath.Dir(checkPath), 0755); err != nil {
		return fmt.Errorf("creating state directory: %w", err)
	}
	if err := os.WriteFile(checkPath, []byte(checkScript), 0755); err != nil {
		return fmt.Errorf("writing check script: %w", err)
	}

	fmt.Printf("PR check armed for %s/%s#%d\n", ident.Owner, ident.Repo, ident.Number)
	fmt.Printf("  PR URL:   %s\n", prURL)
	fmt.Printf("  Head SHA: %s\n", ident.HeadSHA)
	fmt.Printf("  Check:    %s\n", checkPath)
	return nil
}
