package fleet

import (
	"fmt"
	"os"
	"path/filepath"

	"github.com/minhtri2710/munsu/internal/home"
)

// PRCheck runs `munsu pr-check <id> <pr-url>`.
// It captures the full delivery identity (PR URL, head SHA, head ref, base ref,
// owner, repo, provider, and timestamp) in task meta, and writes a check.sh
// script that polls the PR merge status via `gh pr view`.
// On detecting a merged PR, the check.sh script also runs
// `munsu fleet sync` to sync the project clone.
func PRCheck(homeDir string, id, prURL string) error {
	// Capture the full delivery identity atomically
	ident, err := CaptureIdentity(prURL)
	if err != nil {
		return fmt.Errorf("capturing delivery identity: %w", err)
	}

	// Validate identity before persisting
	if err := ValidateIdentity(ident); err != nil {
		return fmt.Errorf("captured identity is incomplete: %w", err)
	}

	// Read existing meta (ignore error if it doesn't exist)
	meta, err := home.ReadMeta(homeDir, id)
	if err != nil {
		meta = make(map[string]string)
	}

	// Write full delivery identity to meta (overwrites legacy pr/pr_head keys too)
	for k, v := range ident.ToMeta() {
		meta[k] = v
	}
	meta["pr"] = prURL                                         // legacy key for compatibility
	meta["pr_head"] = ident.HeadSHA                            // legacy key for compatibility
	meta[MetaDeliveryState] = string(DeliveryStateReviewReady) // initialize lifecycle

	if err := home.WriteMeta(homeDir, id, meta); err != nil {
		return fmt.Errorf("writing task meta: %w", err)
	}

	// Resolve project name for fleet-sync in check.sh script
	project := meta["project"]
	if project == "" {
		project = ident.Repo
	}

	// Write check.sh script
	checkScript := fmt.Sprintf(`#!/bin/bash
# PR merge poll script for task %s
# Generated by munsu pr-check
set -euo pipefail

PR_NUM=%d
OWNER=%s
REPO=%s
HOME_DIR="%s"
PROJECT="%s"

echo "Polling PR #${PR_NUM} merge status for %s/%s..."
RESULT=$(gh pr view "${PR_NUM}" --repo "${OWNER}/${REPO}" --json state 2>&1 || echo "ERROR:$?")

if echo "$RESULT" | grep -q '"state":"MERGED"\|"state": "MERGED"'; then
	echo "merged: true"
	# Best-effort fleet-sync the project clone
	munsu --home "$HOME_DIR" fleet sync "$PROJECT" 2>/dev/null || echo "Warning: fleet sync for ${PROJECT} failed" >&2
elif echo "$RESULT" | grep -q '"state":"OPEN"\|"state": "OPEN"'; then
	echo "merged: false"
	exit 1
elif echo "$RESULT" | grep -q '"state":"CLOSED"\|"state": "CLOSED"'; then
	echo "merged: false (closed)"
	exit 1
else
	echo "error: unexpected response: $RESULT"
	exit 2
fi
`, id, ident.Number, ident.Owner, ident.Repo, homeDir, project, ident.Owner, ident.Repo)

	checkPath := filepath.Join(home.StateDir(homeDir), id+".check")
	if err := os.MkdirAll(filepath.Dir(checkPath), 0755); err != nil {
		return fmt.Errorf("creating state directory: %w", err)
	}
	if err := os.WriteFile(checkPath, []byte(checkScript), 0755); err != nil {
		return fmt.Errorf("writing check script: %w", err)
	}

	fmt.Printf("PR check armed for %s/%s#%d\n", ident.Owner, ident.Repo, ident.Number)
	fmt.Printf("  PR URL:   %s\n", prURL)
	fmt.Printf("  Head SHA: %s\n", ident.HeadSHA)
	fmt.Printf("  Check:    %s\n", checkPath)
	return nil
}
