package fleet

import (
	"errors"
	"fmt"
	"github.com/minhtri2710/munsu/internal/domain"
	"os"
	"path/filepath"

	"github.com/minhtri2710/munsu/internal/home"
	"github.com/minhtri2710/munsu/internal/taskauthority"
)

// RoutePRCheck is the provider-aware entry point for `munsu delivery pr-check`.
// It routes by URL provider: GitHub PRs keep the existing gh-based PRCheck,
// GitLab MRs use MRLiveCheck with the provider-neutral merge-status poll.
// The provider is decided by a pure URL parse, so identity is captured at most
// once (by whichever branch runs); unrecognized URLs fail closed.
func RoutePRCheck(homeDir, id, url string, auth *taskauthority.Authority) error {
	provider, _, _, _, _, err := ParseProviderURL(url)
	if err != nil {
		return fmt.Errorf("pr-check: unsupported PR/MR URL: %w", err)
	}

	switch provider {
	case "github":
		return PRCheck(homeDir, id, url, auth)
	case "gitlab":
		return MRLiveCheck(homeDir, id, url, auth)
	}
	return fmt.Errorf("pr-check: unsupported provider %q for URL %s", provider, url)
}

// MRLiveCheck runs the GitLab MR equivalent of PRCheck.
// It captures the full delivery identity (MR URL, head SHA, source/target branch,
// owner, repo, provider, and timestamp) and routes it through the composed Task
// Authority as the generation-bound delivery preparation (Task 7.5), then
// writes a .check script that invokes the provider-neutral `munsu delivery
// merge-status` command. Never embeds raw glab in the script.
func MRLiveCheck(homeDir string, id, mrURL string, auth *taskauthority.Authority) error {
	if auth == nil {
		return fmt.Errorf("mr-check: requires a composed task authority")
	}

	// Capture the full delivery identity atomically via typed GitLabClient
	ident, err := CaptureIdentity(mrURL)
	if err != nil {
		return fmt.Errorf("capturing delivery identity: %w", err)
	}

	// Validate identity before routing
	if err := domain.ValidateIdentity(ident); err != nil {
		return fmt.Errorf("captured identity is incomplete: %w", err)
	}

	// Route the delivery preparation through the composed Authority (Task
	// 7.5): the generation-bound prepare record commits with the identity
	// and review-ready state, and the identity meta keys are reconciled as a
	// post-commit projection. A projection failure returns a typed partial
	// error and never rolls back the authoritative commit.
	if _, err := StoreDeliveryPrepare(homeDir, auth, id, ident); err != nil {
		var projErr *DeliveryProjectionError
		if errors.As(err, &projErr) {
			fmt.Fprintf(os.Stderr, "Warning: delivery projection failed: %v\n", projErr)
		} else {
			return fmt.Errorf("mr-check: delivery preparation: %w", err)
		}
	}

	// Write provider-neutral .check script that uses the munsu CLI seam
	checkScript := fmt.Sprintf(`#!/bin/bash
# MR merge poll script for task %s
# Generated by munsu mr-check (GitLab)
set -euo pipefail

TASK_ID="%s"
HOME_DIR="%s"

echo "Polling MR merge status for task ${TASK_ID}..."
if munsu --home "$HOME_DIR" delivery merge-status "${TASK_ID}" 2>/dev/null; then
	echo "merged: true"
	exit 0
else
	RESULT=$?
	echo "merged: false (exit code ${RESULT})"
	exit "${RESULT}"
fi
`, id, id, homeDir)

	checkPath := filepath.Join(home.StateDir(homeDir), id+".check")
	if err := os.MkdirAll(filepath.Dir(checkPath), 0755); err != nil {
		return fmt.Errorf("creating state directory: %w", err)
	}
	if err := os.WriteFile(checkPath, []byte(checkScript), 0755); err != nil {
		return fmt.Errorf("writing check script: %w", err)
	}

	fmt.Printf("MR check armed for %s/%s!%d\n", ident.Owner, ident.Repo, ident.Number)
	fmt.Printf("  MR URL:   %s\n", mrURL)
	fmt.Printf("  Head SHA: %s\n", ident.HeadSHA)
	fmt.Printf("  Provider: %s\n", ident.Provider)
	fmt.Printf("  Check:    %s\n", checkPath)
	return nil
}

// MergeStatusError classifies a non-merged delivery status.
type MergeStatusError struct {
	Unverifiable bool
	Err          error
}

func (e *MergeStatusError) Error() string { return e.Err.Error() }
func (e *MergeStatusError) Unwrap() error { return e.Err }

// MergeStatus reports the merge status for a task with a delivery identity.
// Exit status: 0 = merged, 1 = not merged, 2 = error/unverifiable.
// Used as the provider-neutral watcher seam invoked by .check scripts.
func MergeStatus(homeDir, id string) error {
	ident, err := RequireIdentity(homeDir, id)
	if err != nil {
		return &MergeStatusError{Unverifiable: true, Err: fmt.Errorf("cannot read delivery identity: %w", err)}
	}

	status, err := QueryDeliveryMergeStatus(ident)
	if err != nil {
		return &MergeStatusError{Unverifiable: true, Err: fmt.Errorf("merge status query: %w", err)}
	}

	if status.Merged {
		fmt.Printf("%s/%s#%d merged (state=%s, head=%s)\n",
			ident.Owner, ident.Repo, ident.Number, status.State, status.HeadSHA)
		return nil
	}

	if status.Closed {
		fmt.Printf("%s/%s#%d closed (not merged, state=%s)\n",
			ident.Owner, ident.Repo, ident.Number, status.State)
		return &MergeStatusError{Err: fmt.Errorf("MR %d is closed but not merged (state=%s)", ident.Number, status.State)}
	}

	fmt.Printf("%s/%s#%d open (not merged, state=%s)\n",
		ident.Owner, ident.Repo, ident.Number, status.State)
	return &MergeStatusError{Err: fmt.Errorf("MR %d is open and not merged (state=%s)", ident.Number, status.State)}
}
